### ISSUE TITLE
Compilation Instructions?

### ISSUE THREAD

**Issue by Thysbelon** [chrg127/libgsf#1]
I'm having some trouble compiling the library.
I created the directory `build` in `libgsf`, went into `build`, then ran the commands `cmake -D CMAKE_C_COMPILER="/usr/bin/gcc-10" -D CMAKE_CXX_COMPILER="/usr/bin/g++-10" ../` and `make`.  I received [many errors](https://github.com/chrg127/libgsf/files/13654737/errors.txt) when I ran `make`.
I am using Windows 11 22H2, Windows Subsystem for Linux 2.0.9.0, and Ubuntu 20.04.6 LTS.
If you can spot a simple mistake that I am making, I would appreciate your help.

**Comment by chrg127** [comment]
Hello there.

No, you aren't making any mistakes. These compilation errors were caused by your compiler versions: it seems that, on GCC 10, the comparison function for std::unordered_map can't be constexpr (as well some other details, if you're curious you can find more information here: https://github.com/chrg127/libgsf/commit/1fcc008882cc8ac376f8c88bb59c967b2a013341).

Anyway, I've fixed these errors now.

As an aside, this library, while certainly usable, is not 100% complete. That's why there's no README or anything else yet. (the remaining stuff to do would be only a few additional features + adding some stuff to the build script, but still)

**Comment by Thysbelon** [comment]
Thank you.
